### ISSUE TITLE
requirements line 34

### ISSUE THREAD

**Issue by gainaaa** [adsau59/fishyboteso#1]
On: pip install -r requirements.txt

Collecting win32core==221.36 (from -r requirements.txt (line 34))
  Could not find a version that satisfies the requirement win32core==221.36 (from -r requirements.txt (line 34)) (from versions: 221.2, 221.3, 221.4, 221.5, 221.6, 221.7, 221.12, 221.14, 221.15, 221.16, 221.18, 221.20, 221.21, 221.22, 221.23, 221.24, 221.25, 221.26, 221.27, 221.28)

And on python fishy.py: 

File "C:\Users\*\*\fishyboteso-master\init.py", line 21, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

**Comment by adsau59** [comment]
sorry for the late reply,

It looks like win32 api is not getting download, try removing that from `requirements.txt` file and insteall the rest modules,

to install win32 api u can use, `pip install pypiwin32` command
