### ISSUE TITLE
Getting random Timeout Errors 

### ISSUE THREAD

**Issue by neoxer** [adsau59/fishyboteso#10]
It worked for a day then now after one fishing it won't catch it just write out a Timeout Error

**Comment by adsau59** [comment]
can u send me a screenshot of the game and the bot, when that happens?

**Comment by adsau59** [comment]
the issue got resolved? if so can u specify what happened so that it might help others too

**Comment by neoxer** [comment]
> the issue got resolved? if so can u specify what happened so that it might help others too

I reinstalled the fishybot, nothing. But after reinstalling the Addon which is a requirement then works fine now. :)

 I dont know what happened when it's stopped working but when I went to the debug label end started a PixelVal its returned with two or three Timeout Errors. Maybe you better know what happened :D

**Comment by adsau59** [comment]
strange... addon should be automatically installed by the bot. if you get the error again, try sending me its screenshot
