### ISSUE TITLE
Random sleep time request

### ISSUE THREAD

**Issue by Rain0Ash** [adsau59/fishyboteso#12]
Greetings. I want to offer the ability to adjust the reaction time.
Something of

```
from random import gauss
def reaction_time():
    max = 0.33
    min = 0.15

    reaction = gauss(0.225, 0.6)
    if (reaction < min): return min
    if (reaction > max): return max
    return reaction

    ...
    sleep(reaction_time())
```

**Comment by Jasems** [comment]
Is this something I can add via the code above?

**Comment by Rain0Ash** [comment]
This roughly shows how can make a delay.
This function is called when there is a delay before the action in the game (start fishing; catch fish; pick up loot)

You can experiment with the coefficients of the Gaussian function.

It will not be worse from using this function, however. If actions are logged on the server, this will add a reaction delay similar to that of a real person.
