### ISSUE TITLE
Character ducks and opens inventory instead of Fishing

### ISSUE THREAD

**Issue by Lanqu** [adsau59/fishyboteso#14]
It looks like duck and inventory buttons were pressed instead of E
Sometimes it is working, but more often is not

**Comment by adsau59** [comment]
please contact me on discord so that we can resolve the issue

**Comment by adsau59** [comment]
fixed for 0.3.14, try updating fishy bot, it should fix the issue
if it doesn't update automatically try using this command `python -m pip install fishy --upgrade`
