### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Qrimetime** [adsau59/fishyboteso#8]
Can you make it so the bot uses different eso settings so that we can have normal Windows tot regular play and smaller Windows for the bot to work.

Ps didn t know where to put the request, sorry if it is in the wrong tab

**Comment by adsau59** [comment]
thanks for the recommendation, I have fixed the bug which prevented the game to run in full screen while the bot is running, please follow the updated readme to reconfigure the bot. Also, you will need to update the Addon from the repository.
